# Dependencies
markdown:         kramdown
remote_theme:     broccolini/swiss

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            DJ-consulting
tagline:          'data science'
description:      'We tune the world with data science'
url:              https://sample.com
baseurl:          '/'

author:
  name:           'Jinjun Sun'
  url:            https://twitter.com/jsunster

paginate:         5

# Custom vars
version:          2.1.0

# github:
#   repo:           https://github.com/poole/hyde

plugins:
  - jekyll-paginate
  - jekyll-gist 
